# ---- /etc/nginx/sites-enabled/wic-uploader ----
server {
    server_name wic-krakow.sanctumsec.com;

    client_max_body_size 110M;

    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/wic-krakow.sanctumsec.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/wic-krakow.sanctumsec.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = wic-krakow.sanctumsec.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name wic-krakow.sanctumsec.com;
    return 404; # managed by Certbot


}